apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-enterprise-license
  namespace: {{ .Values.global.namespace }}
  annotations:
    avp.kubernetes.io/path: "secret/data/hub/{{ $.Values.global.name }}"
type: Opaque
stringData:
  license: <license>