apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: license
  namespace: kong
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ .Values.global.name }}-enterprise-license
    template:
      type: Opaque
      data:
        license: |-
          {{ "{{ .mysecret | toString }}" }}
  data:
  - secretKey: mysecret
    remoteRef:
      key: {{ $.Values.secretsBase.key }}/{{ $.Values.global.name }}
      property: license