apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.name }}-gitops
  namespace: {{ .Values.global.namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.name }}-jobs
rules:
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
    verbs:
      - get
  - verbs:
      - create
      - get
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
      - services
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.name }}-role
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.name }}-jobs-cluster-binding
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.global.namespace }}
    name: {{ .Values.global.name }}-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.name }}-jobs
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.name }}-jobs-binding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.name }}-gitops
    namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.global.name }}-role